import { useEffect, useRef, useState } from 'react'
import styles from './KageStage.module.css'

/**
 * Boots the authored Kage experience inside a React route.
 *
 * Not an iframe, and not a second renderer: this mounts *the* Kage document —
 * its markup, its stylesheet and its script — into the live page, so the
 * scene, camera, scroll choreography, particles, fog, foreground staging and
 * pointer handling are the authored ones, running in the host document.
 *
 * The page it loads is generated by `scripts/build-fandomverse-kage.mjs` from
 * the untouched `kage.html`, so the engine stays upstream and only its content
 * is FandomVerse's.
 *
 * WHY THE SHIMS
 * The Kage script is an IIFE written for a document it owns for the page's
 * lifetime: it registers animation frames and window listeners and never
 * removes them, because standalone it never has to. Inside a router it does
 * have to — leaving it running after the route unmounts would burn a WebGL
 * context and a render loop for the rest of the session. So `requestAnimationFrame`
 * and `addEventListener` are wrapped for the duration of the boot, every
 * registration is recorded, and teardown undoes exactly what the boot did.
 * Nothing in the Kage source is modified to achieve this.
 */

const PAGE_URL = '/landing-pages/fandomverse-kage.html'
const PAGE_BASE = '/landing-pages/'
const MARKER = 'data-kage-stage'

type Cleanup = () => void

/**
 * The teardown for whichever stage is currently live, held at module scope.
 *
 * `KageStage` can be mounted, unmounted and mounted again — React does this
 * routinely, and StrictMode does it on purpose. The boot is asynchronous, so
 * two runs can otherwise overlap: the second appends the Kage document while
 * the first is still in flight, and whichever cleanup runs last sweeps nodes
 * the other still depends on. That is exactly how navigating from `/` into a
 * hub ended up with a whole second temple in the page.
 *
 * Every mount tears down its predecessor before it appends anything, so there
 * is never more than one stage in the document.
 */
let liveTeardown: Cleanup | null = null

/**
 * Bumped by every mount. A boot carries the generation it started in and
 * abandons itself the moment a newer one exists — without this, a boot still
 * in flight when its own route unmounted would go on appending the Kage
 * document *after* teardown had swept, which left the stylesheet behind on
 * the next page.
 */
let generation = 0

/** Records every frame and listener the Kage boot registers, so both can be undone. */
function installShims(): { restore: Cleanup; teardown: Cleanup } {
  const frames = new Set<number>()
  const listeners: Array<[EventTarget, string, EventListenerOrEventListenerObject, unknown]> = []

  const realRaf = window.requestAnimationFrame.bind(window)
  const realCancel = window.cancelAnimationFrame.bind(window)

  window.requestAnimationFrame = (cb: FrameRequestCallback) => {
    const id = realRaf((t) => {
      frames.delete(id)
      cb(t)
    })
    frames.add(id)
    return id
  }

  const patched: Array<[EventTarget, typeof EventTarget.prototype.addEventListener]> = []
  for (const target of [window, document, document.documentElement, document.body] as EventTarget[]) {
    const real = target.addEventListener.bind(target)
    patched.push([target, target.addEventListener])
    target.addEventListener = ((type: string, fn: EventListenerOrEventListenerObject, opts?: unknown) => {
      listeners.push([target, type, fn, opts])
      return real(type, fn, opts as AddEventListenerOptions)
    }) as typeof target.addEventListener
  }

  return {
    restore() {
      window.requestAnimationFrame = realRaf
      for (const [target, original] of patched) target.addEventListener = original
    },
    teardown() {
      for (const id of frames) realCancel(id)
      frames.clear()
      for (const [target, type, fn, opts] of listeners) {
        try {
          target.removeEventListener(type, fn, opts as EventListenerOptions)
        } catch {
          /* one stubborn listener must not abort the rest of the teardown */
        }
      }
      listeners.length = 0
    },
  }
}

/** Relative asset references resolve against `/`, not `/landing-pages/`, once injected. */
function absolutise(html: string): string {
  return html
    .replace(/(src|href)="secret-pathways-assets\//g, `$1="${PAGE_BASE}secret-pathways-assets/`)
    .replace(/url\((['"]?)secret-pathways-assets\//g, `url($1${PAGE_BASE}secret-pathways-assets/`)
}

export function KageStage() {
  const hostRef = useRef<HTMLDivElement | null>(null)
  const [failed, setFailed] = useState<string | null>(null)
  // The document has to be fetched, parsed and injected before Kage's own
  // preloader exists to cover the screen. Without something in that gap the
  // route is an empty white frame, which reads as a broken page rather than
  // as a loading one — and on a cold dev server the gap is seconds, not
  // milliseconds.
  const [booted, setBooted] = useState(false)

  useEffect(() => {
    // Any stage still live from a previous mount goes first.
    liveTeardown?.()
    liveTeardown = null

    let disposed = false
    /**
     * Removes everything the stage put in the document.
     *
     * Swept by selector rather than by the captured array: the array only
     * knows what this run appended, and a remount leaves an earlier run's
     * nodes with nobody to remove them.
     */
    const sweepDom = () => {
      for (const node of Array.from(
        document.querySelectorAll(`[${MARKER}], #fg-sky, #pre, .cursor`),
      )) {
        node.remove()
      }
      injectedHead.length = 0
    }

    /**
     * Leaving the landing sweeps immediately, rather than waiting for React to
     * unmount this component.
     *
     * Measured: unmount lands about three seconds after the click, because
     * tearing the scene down is heavy work queued behind the route change. For
     * those three seconds the Kage stylesheet — which targets `html`, `body`
     * and every Kage class — was still applied to the page the visitor had
     * already arrived on. The route changing is the earliest honest signal
     * that this stage is no longer wanted.
     */
    const onRouteLeft = () => {
      const hash = window.location.hash
      if (hash === '' || hash === '#' || hash === '#/') return
      disposed = true
      sweepDom()
    }
    window.addEventListener('hashchange', onRouteLeft)

    const myGeneration = ++generation
    /** True once this run is either torn down or superseded. */
    const stale = () => disposed || myGeneration !== generation

    if (!hostRef.current) return
    // Captured as a definitely-assigned local: the narrowing above does not
    // reach into the async boot closure below.
    const host: HTMLDivElement = hostRef.current

    const injectedHead: Element[] = []
    let shims: ReturnType<typeof installShims> | null = null
    const bodyClasses: string[] = []

    async function boot() {
      const response = await fetch(PAGE_URL)
      if (!response.ok) throw new Error(`${response.status} ${response.statusText}`)
      const parsed = new DOMParser().parseFromString(absolutise(await response.text()), 'text/html')
      if (stale()) return

      // 1 · the page's own styles, tagged so teardown can find them again.
      for (const node of Array.from(parsed.head.querySelectorAll('style, link[rel="stylesheet"]'))) {
        // Checked per node, not once per phase: a teardown landing mid-loop
        // would otherwise leave the rest of the sheets in the head.
        if (stale()) return
        const clone = node.cloneNode(true) as Element
        clone.setAttribute(MARKER, '')
        document.head.appendChild(clone)
        injectedHead.push(clone)
      }

      if (stale()) return

      // 2 · the markup, minus its scripts, which have to run in order below.
      const scripts = Array.from(parsed.body.querySelectorAll('script'))
      for (const script of scripts) script.remove()
      host.append(...Array.from(parsed.body.childNodes))

      // The Kage stylesheet styles `body` directly, and its boot removes
      // `is-locked` once the preloader finishes.
      for (const cls of Array.from(parsed.body.classList)) {
        if (!document.body.classList.contains(cls)) {
          document.body.classList.add(cls)
          bodyClasses.push(cls)
        }
      }

      // 3 · three.js first, then the scene script, both recorded by the shims.
      shims = installShims()
      try {
        for (const script of scripts) {
          if (stale()) return
          if (script.src) {
            await new Promise<void>((resolve, reject) => {
              const tag = document.createElement('script')
              tag.src = new URL(script.getAttribute('src')!, window.location.origin + PAGE_BASE).pathname
              tag.setAttribute(MARKER, '')
              tag.onload = () => resolve()
              tag.onerror = () => reject(new Error(`failed to load ${tag.src}`))
              document.head.appendChild(tag)
              injectedHead.push(tag)
            })
          } else {
            const tag = document.createElement('script')
            tag.textContent = script.textContent
            tag.setAttribute(MARKER, '')
            document.head.appendChild(tag)
            injectedHead.push(tag)
          }
        }
        // The boot itself is deferred by a `setTimeout(boot, 0)` inside the
        // script, so one more turn of the loop is needed before it has run.
        await new Promise((r) => setTimeout(r, 0))
        if (!stale()) setBooted(true)
      } catch (error) {
        shims.restore()
        throw error
      }
      // Deliberately NOT restored here. The render loop re-queues itself every
      // frame, and a frame requested after the shim came off would be invisible
      // to teardown — which is exactly what happened: one more frame ran after
      // the context had been released and three.js threw from acquireProgram.
      // The shim is a thin passthrough that only records ids, and it comes off
      // in the cleanup below.
    }

    boot().catch((error: unknown) => {
      if (!stale()) setFailed(error instanceof Error ? error.message : String(error))
    })

    const teardown = () => {
      disposed = true

      /**
       * Every step is isolated.
       *
       * This teardown used to run as one block, and a throw in an early step
       * silently skipped the DOM sweep below it — which is exactly what left
       * the Kage stylesheet in the head after navigating from `/` into a hub.
       * That sheet styles `html`, `body` and every Kage class globally, so the
       * next page inherited a temple's worth of rules it never asked for.
       * Nothing here may prevent anything after it from running.
       */
      const step = (work: () => void) => {
        try {
          work()
        } catch {
          /* one failed step must never abort the rest of the teardown */
        }
      }

      // The DOM comes out first, because it is what the visitor can see.
      step(sweepDom)
      step(() => {
        for (const cls of bodyClasses) document.body.classList.remove(cls)
      })
      step(() => {
        host.textContent = ''
      })

      // Then the machinery. Order matters here: stop the loop before releasing
      // the context, or a queued frame renders against a dead one.
      step(() => window.removeEventListener('hashchange', onRouteLeft))
      step(() => shims?.teardown())
      step(() => shims?.restore())
      step(() => {
        const kage = (
          window as unknown as {
            __kage?: { renderer?: { dispose?: () => void; forceContextLoss?: () => void } }
          }
        ).__kage
        kage?.renderer?.forceContextLoss?.()
        kage?.renderer?.dispose?.()
      })
      step(() => {
        delete (window as unknown as { __kage?: unknown }).__kage
        delete (window as unknown as { __secret?: unknown }).__secret
      })

      // One more sweep on the next macrotask. The boot is asynchronous and can
      // only be *asked* to stop — an append already queued behind an `await`
      // still lands after this teardown has run. The synchronous sweep above
      // catches the common case; this catches the straggler, which is how the
      // Kage stylesheet was still reaching category pages intermittently.
      // The invariant, checked rather than inferred: if no stage is mounted,
      // nothing the stage injected may remain. Generation bookkeeping proved
      // too fragile here — a remount could make a live stage look stale and a
      // straggling append look current. Twice, because a boot blocked on an
      // `await` can land after the first pass.
      const sweepIfNoStage = () => {
        if (document.querySelector('[data-testid="kage-stage"]')) return
        for (const late of Array.from(
          document.querySelectorAll(`[${MARKER}], #fg-sky, #pre, .cursor`),
        )) {
          late.remove()
        }
      }
      // A bounded cleanup window rather than a single pass. The boot blocks on
      // a ~250 KB fetch and a full DOM parse, and it cannot be force-cancelled
      // mid-flight — only asked to stop. Measured: the stage unmounts at
      // ~1.5s while a straggling append could still land after that, so the
      // window covers it. Every pass is a no-op once the head is clear or a
      // new stage has mounted.
      for (const delay of [0, 300, 800, 1500, 2500]) {
        setTimeout(sweepIfNoStage, delay)
      }
    }

    liveTeardown = teardown
    return () => {
      teardown()
      if (liveTeardown === teardown) liveTeardown = null
    }
  }, [])

  return (
    <>
      <div ref={hostRef} className={styles.host} data-testid="kage-stage" />

      {!booted && !failed ? (
        <div className={styles.boot} role="status" aria-live="polite">
          <p className={styles.bootBrand}>FandomVerse</p>
          <p className={styles.bootNote}>Opening the universe…</p>
        </div>
      ) : null}

      {failed ? (
        <div className={styles.boot} role="status">
          <p className={styles.bootBrand}>FandomVerse</p>
          <p className={styles.bootNote}>
            The cinematic landing could not load ({failed}).
          </p>
          <p className={styles.bootNote}>
            <a className={styles.bootLink} href="/#/anime">
              Enter the universe
            </a>
          </p>
        </div>
      ) : null}
    </>
  )
}
