import { describe, it, expect } from 'vitest'
import {
  categories,
  articles,
  characters,
  events,
  media,
  galleries,
  releases,
  merchandise,
  resolveRelatedContent,
} from './index'
import { CATEGORY_ROUTES } from '../routes/categoryRoutes'
import type { AssetRef } from '../types/content'

/**
 * SRS content-minimum + referential-integrity gate (Phase 5, Director
 * instruction §17). This test exists specifically to fail loudly if the
 * dataset ever drops below the SRS-mandated quantities (FR-019: 5
 * characters per category; FR-022: 3 events per category) or if any
 * reference in the dataset stops resolving. Content is regenerated by
 * scripts/generate-content.mjs — these assertions are what keep that
 * script honest.
 */

const SRS_CATEGORY_COUNT = 7
const SRS_MIN_CHARACTERS_PER_CATEGORY = 5
const SRS_MIN_EVENTS_PER_CATEGORY = 3

/**
 * Real files present under public/assets/generated, resolved at transform
 * time. Vite's glob is used rather than node:fs on purpose: tsconfig.app
 * deliberately excludes Node types so browser-only app code can't reach
 * for `fs`/`process`, and this test lives under src/.
 */
const assetFilesOnDisk = new Set(
  Object.keys(import.meta.glob('/public/assets/generated/**/*.{svg,png,jpg}')).map((path) =>
    path.replace('/public', ''),
  ),
)

const categoryIds = categories.map((category) => category.id)

/** Every dataset entity that carries an id, flattened for uniqueness/reference checks. */
const allEntities = [
  ...categories.map((c) => ({ id: c.id, kind: 'category' as const })),
  ...articles.map((a) => ({ id: a.id, kind: 'article' as const })),
  ...characters.map((c) => ({ id: c.id, kind: 'character' as const })),
  ...events.map((e) => ({ id: e.id, kind: 'event' as const })),
  ...media.map((m) => ({ id: m.id, kind: 'media' as const })),
  ...galleries.map((g) => ({ id: g.id, kind: 'gallery' as const })),
  ...releases.map((r) => ({ id: r.id, kind: 'release' as const })),
  ...merchandise.map((m) => ({ id: m.id, kind: 'merchandise' as const })),
]

function assetPaths(): Array<{ owner: string; asset: AssetRef }> {
  return [
    ...categories.map((c) => ({ owner: c.id, asset: c.heroImage })),
    ...articles.map((a) => ({ owner: a.id, asset: a.thumbnail })),
    ...characters.map((c) => ({ owner: c.id, asset: c.image })),
    ...events.map((e) => ({ owner: e.id, asset: e.image })),
    ...media.map((m) => ({ owner: m.id, asset: m.thumbnail })),
    ...releases.map((r) => ({ owner: r.id, asset: r.coverImage })),
    ...merchandise.map((m) => ({ owner: m.id, asset: m.image })),
    ...galleries.flatMap((g) => g.images.map((image) => ({ owner: image.id, asset: image }))),
  ]
}

describe('SRS content minimums', () => {
  it(`has exactly ${SRS_CATEGORY_COUNT} canonical categories`, () => {
    expect(categories).toHaveLength(SRS_CATEGORY_COUNT)
    expect(new Set(categoryIds).size).toBe(SRS_CATEGORY_COUNT)
  })

  it('has one route per category, and one category per route (no second registry)', () => {
    expect(CATEGORY_ROUTES).toHaveLength(SRS_CATEGORY_COUNT)
    expect([...CATEGORY_ROUTES.map((route) => route.categoryId)].sort()).toEqual([...categoryIds].sort())
    for (const route of CATEGORY_ROUTES) {
      const category = categories.find((item) => item.id === route.categoryId)
      expect(category, `route "${route.path}" has no matching category`).toBeDefined()
      expect(category?.slug, `category "${route.categoryId}" slug must match its route path`).toBe(route.path)
    }
  })

  it.each(categoryIds)(
    `category "%s" has at least ${SRS_MIN_CHARACTERS_PER_CATEGORY} character profiles (FR-019)`,
    (categoryId) => {
      const count = characters.filter((character) => character.categoryId === categoryId).length
      expect(count).toBeGreaterThanOrEqual(SRS_MIN_CHARACTERS_PER_CATEGORY)
    },
  )

  it.each(categoryIds)(
    `category "%s" has at least ${SRS_MIN_EVENTS_PER_CATEGORY} events (FR-022)`,
    (categoryId) => {
      const count = events.filter((event) => event.categoryId === categoryId).length
      expect(count).toBeGreaterThanOrEqual(SRS_MIN_EVENTS_PER_CATEGORY)
    },
  )

  it('meets the SRS totals of 35 characters and 21 events overall', () => {
    expect(characters.length).toBeGreaterThanOrEqual(SRS_CATEGORY_COUNT * SRS_MIN_CHARACTERS_PER_CATEGORY)
    expect(events.length).toBeGreaterThanOrEqual(SRS_CATEGORY_COUNT * SRS_MIN_EVENTS_PER_CATEGORY)
  })

  it.each(categoryIds)('category "%s" has gallery, article, trailer, release, and merchandise content', (categoryId) => {
    expect(articles.filter((item) => item.categoryId === categoryId).length).toBeGreaterThan(0)
    expect(galleries.filter((item) => item.categoryId === categoryId).length).toBeGreaterThan(0)
    expect(media.filter((item) => item.categoryId === categoryId && item.mediaType === 'trailer').length).toBeGreaterThan(0)
    expect(releases.filter((item) => item.categoryId === categoryId).length).toBeGreaterThan(0)
    expect(merchandise.filter((item) => item.categoryId === categoryId).length).toBeGreaterThan(0)
  })

  it('has exactly one featured article per category', () => {
    for (const categoryId of categoryIds) {
      const featured = articles.filter((item) => item.categoryId === categoryId && item.featured)
      expect(featured, `category "${categoryId}" featured article count`).toHaveLength(1)
    }
  })
})

describe('content referential integrity', () => {
  it('has globally unique entity ids', () => {
    const seen = new Map<string, string>()
    const duplicates: string[] = []
    for (const entity of allEntities) {
      if (seen.has(entity.id)) {
        duplicates.push(`${entity.id} (${seen.get(entity.id)} and ${entity.kind})`)
      }
      seen.set(entity.id, entity.kind)
    }
    expect(duplicates).toEqual([])
  })

  it('has unique gallery image ids', () => {
    const imageIds = galleries.flatMap((gallery) => gallery.images.map((image) => image.id))
    expect(new Set(imageIds).size).toBe(imageIds.length)
  })

  it.each([
    ['articles', articles],
    ['characters', characters],
    ['events', events],
    ['media', media],
    ['galleries', galleries],
    ['releases', releases],
    ['merchandise', merchandise],
  ] as const)('every %s entry points at a real category', (label, collection) => {
    const orphans = collection
      .filter((item) => !categoryIds.includes(item.categoryId))
      .map((item) => `${label}:${item.id} -> ${item.categoryId}`)
    expect(orphans).toEqual([])
  })

  it('has no orphan relatedIds anywhere in the dataset', () => {
    const withRelated: Array<{ id: string; relatedIds: string[] }> = [
      ...articles.map((item) => ({ id: item.id, relatedIds: item.relatedIds ?? [] })),
      ...characters.map((item) => ({ id: item.id, relatedIds: item.relatedIds ?? [] })),
      ...events.map((item) => ({ id: item.id, relatedIds: item.relatedIds ?? [] })),
    ]

    const orphans: string[] = []
    for (const entity of withRelated) {
      const resolved = resolveRelatedContent(entity.relatedIds)
      if (resolved.length !== entity.relatedIds.length) {
        const resolvedIds = new Set(resolved.map((item) => item.id))
        orphans.push(
          ...entity.relatedIds.filter((id) => !resolvedIds.has(id)).map((id) => `${entity.id} -> ${id}`),
        )
      }
    }
    expect(orphans).toEqual([])
  })

  it('never lists an entity as its own related content', () => {
    const selfReferences = [...articles, ...characters, ...events]
      .filter((item) => (item.relatedIds ?? []).includes(item.id))
      .map((item) => item.id)
    expect(selfReferences).toEqual([])
  })
})

describe('required fields', () => {
  it('every category carries its full registry metadata', () => {
    for (const category of categories) {
      expect(category.id, 'category id').toBeTruthy()
      expect(category.slug, `${category.id} slug`).toBeTruthy()
      expect(category.name, `${category.id} name`).toBeTruthy()
      expect(category.description.length, `${category.id} description`).toBeGreaterThan(40)
      expect(category.accentColor, `${category.id} accent token`).toMatch(/^--color-accent-/)
      expect(category.visualMotif, `${category.id} visual motif`).toBeTruthy()
      expect(category.franchise, `${category.id} franchise`).toBeTruthy()
    }
  })

  it('every character carries the fields the profile page renders', () => {
    for (const character of characters) {
      expect(character.name, `${character.id} name`).toBeTruthy()
      expect(character.role, `${character.id} role`).toBeTruthy()
      expect(character.series, `${character.id} series`).toBeTruthy()
      expect(character.biography.length, `${character.id} biography`).toBeGreaterThan(40)
      expect(character.traits.length, `${character.id} traits`).toBeGreaterThan(0)
      expect(character.tags.length, `${character.id} tags`).toBeGreaterThan(0)
    }
  })

  it('every event carries the fields the event page renders', () => {
    for (const event of events) {
      expect(event.title, `${event.id} title`).toBeTruthy()
      expect(event.date, `${event.id} date`).toMatch(/^\d{4}-\d{2}-\d{2}$/)
      expect(event.location, `${event.id} location`).toBeTruthy()
      expect(event.description.length, `${event.id} description`).toBeGreaterThan(40)
      expect(['convention', 'watch-party', 'meetup', 'other']).toContain(event.eventType)
      expect(['past', 'upcoming']).toContain(event.status)
    }
  })

  it('every article carries the fields the article page renders', () => {
    for (const article of articles) {
      expect(article.title, `${article.id} title`).toBeTruthy()
      expect(article.summary.length, `${article.id} summary`).toBeGreaterThan(20)
      expect(article.body.length, `${article.id} body`).toBeGreaterThan(100)
      expect(article.publishedDate, `${article.id} publishedDate`).toMatch(/^\d{4}-\d{2}-\d{2}$/)
      expect(article.tags.length, `${article.id} tags`).toBeGreaterThan(0)
    }
  })

  it('every merchandise item has a usable price range and availability status', () => {
    for (const item of merchandise) {
      expect(item.priceRangeMin, `${item.id} min price`).toBeGreaterThan(0)
      expect(item.priceRangeMax, `${item.id} max price`).toBeGreaterThanOrEqual(item.priceRangeMin)
      expect(item.currency, `${item.id} currency`).toBeTruthy()
      expect(['available', 'coming-soon', 'sold-out']).toContain(item.status)
    }
  })

  it('every release carries a date, type, and status', () => {
    for (const release of releases) {
      expect(release.releaseDate, `${release.id} date`).toMatch(/^\d{4}-\d{2}-\d{2}$/)
      expect(release.type, `${release.id} type`).toBeTruthy()
      expect(['upcoming', 'recent', 'archived']).toContain(release.status)
    }
  })
})

describe('honesty labelling (no fabricated real-world claims)', () => {
  it('labels every event, release, and trailer as fiction', () => {
    expect(events.every((event) => event.fictional)).toBe(true)
    expect(releases.every((release) => release.fictional)).toBe(true)
    expect(media.every((item) => item.fictional)).toBe(true)
  })

  it('does not ship a live external embed for any fictional trailer', () => {
    for (const item of media) {
      expect(item.embedUrl, `${item.id} must not point at an external streaming URL`).toBe('')
    }
  })
})

describe('asset integrity', () => {
  it('finds the generated asset files on disk at all (guards the check itself)', () => {
    expect(assetFilesOnDisk.size).toBeGreaterThan(100)
  })

  it('every declared asset resolves to a real file on disk', () => {
    const missing = assetPaths()
      .filter(({ asset }) => !assetFilesOnDisk.has(asset.src))
      .map(({ owner, asset }) => `${owner} -> ${asset.src}`)
    expect(missing).toEqual([])
  })

  it('every declared asset has non-empty alt text and recorded provenance', () => {
    const problems: string[] = []
    for (const { owner, asset } of assetPaths()) {
      if (!asset.alt || asset.alt.trim().length < 10) problems.push(`${owner}: weak alt text`)
      if (!asset.credit) problems.push(`${owner}: missing provenance credit`)
    }
    expect(problems).toEqual([])
  })
})
