/**
 * Typed access to the static content dataset. All imports below are
 * build-time static JSON — never fetched, never mutated at runtime
 * (docs/00_PROJECT_CONSTITUTION.md CR-001).
 *
 * The content collections are generated by scripts/generate-content.mjs
 * (never hand-edited) and held to the SRS minimums — 7 categories, ≥5
 * characters and ≥3 events per category (FR-019/FR-022) — by
 * ./contentValidation.test.ts, which fails the build if any of them, any
 * cross-reference, or any declared asset regresses.
 *
 * faqs.json and chatbot.json remain seed data; the chatbot rule engine is
 * a later phase (D-004).
 */
import categoriesData from './categories.json'
import articlesData from './articles.json'
import charactersData from './characters.json'
import eventsData from './events.json'
import merchandiseData from './merchandise.json'
import mediaData from './media.json'
import galleriesData from './galleries.json'
import releasesData from './releases.json'
import faqsData from './faqs.json'
import chatbotData from './chatbot.json'

import type {
  Category,
  Article,
  Character,
  EventItem,
  MerchandiseItem,
  MediaItem,
  Gallery,
  Release,
  Faq,
  ChatbotConfig,
} from '../types/content'

export const categories = categoriesData as Category[]
export const articles = articlesData as Article[]
export const characters = charactersData as Character[]
export const events = eventsData as EventItem[]
export const merchandise = merchandiseData as MerchandiseItem[]
export const media = mediaData as MediaItem[]
export const galleries = galleriesData as Gallery[]
export const releases = releasesData as Release[]
export const faqs = faqsData as Faq[]
export const chatbotConfig = chatbotData as ChatbotConfig

export function getCategoryById(id: string): Category | undefined {
  return categories.find((category) => category.id === id)
}

/** Resolves either a Category.id ("kpop") or its route slug ("k-pop") — used by the generic `/category/:slug` route, since the two differ for K-Pop. */
export function getCategoryByIdOrSlug(value: string): Category | undefined {
  return categories.find((category) => category.id === value || category.slug === value)
}

export interface RelatedContentRef {
  id: string
  type: 'article' | 'character' | 'event' | 'merchandise'
  title: string
  path: string
}

/**
 * Resolves a mixed list of `relatedIds` (which may reference articles,
 * characters, events, or merchandise) into displayable {title, path}
 * entries. Any id that resolves to nothing is silently dropped rather than
 * rendered as a broken link — the content-validation test
 * (src/data/contentValidation.test.ts) is what actually enforces that no
 * orphan references exist in the dataset.
 */
export function resolveRelatedContent(ids: string[] = []): RelatedContentRef[] {
  const results: RelatedContentRef[] = []
  for (const id of ids) {
    const article = articles.find((item) => item.id === id)
    if (article) {
      results.push({ id, type: 'article', title: article.title, path: `/article/${id}` })
      continue
    }
    const character = characters.find((item) => item.id === id)
    if (character) {
      results.push({ id, type: 'character', title: character.name, path: `/character/${id}` })
      continue
    }
    const event = events.find((item) => item.id === id)
    if (event) {
      results.push({ id, type: 'event', title: event.title, path: `/event/${id}` })
      continue
    }
    const merchItem = merchandise.find((item) => item.id === id)
    if (merchItem) {
      results.push({ id, type: 'merchandise', title: merchItem.name, path: `/product/${id}` })
    }
  }
  return results
}
